### ISSUE TITLE
Missing user & date of migration metadata

### ISSUE THREAD

**Issue by seth-shaw** [seth-shaw/DataAccessioner#4]
Quote from an email:

> "Your Name" field does not transfer over anywhere into the XML file.  Is it somewhere else?  What about a date that the XML file was written?  It documents which schema it is using, but there is no date associated with the XML file itself.  It would seem like both of these fields would be useful for provenance purposes.

Note that the 0.3.1 version (and earlier) provide this as a note within the disk's folder node. This feature was unintentionally omitted during the v1 rewrite.

Possible options:
- _Easier:_ Modify the swing-view and metadata manager to create a note akin to the earlier versions.
- _More difficult but probably better:_ Create a new PREMIS event for the entire source (add a link each file?) OR for each individual file.

**Comment by sprater** [comment]
Fixed in 1.1 with addition of ingest_note element to XML.  Example:  <ingest_note>Sample Collection transferred by Bugs Bunny on Tue Jan 10 11:48:09 CST 2017</ingest_note>

See commit 97ef2d9da75e03f7757697e41da9d18744817e0e
