### ISSUE TITLE
Logging output for job time estimates

### ISSUE THREAD

**Issue by krdyke** [seth-shaw/DataAccessioner#8]
Hi Seth,

In the interest of helping our curators track time while accessioning electronic records, I've made a few changes to DA to output a daily rolling log file that indicates when a job starts and finishes. Seeing as it's fairly minor (and I'm not really a Java guy), I didn't want to presume to create a PR, but would be happy to. 

Here's what I've done:

https://github.com/seth-shaw/DataAccessioner/compare/1.0-dev...krdyke:1.0-dev

I wanted to give you a heads up because I'm writing a blog post for the bloggERS (see the call [here](https://saaers.wordpress.com/2016/03/04/request-for-contributors-to-a-new-series-on-bloggers/)).

Thanks!

**Comment by sprater** [comment]
Hello, Kevin --

I'll be incorporating your changes into version 1.1 of Data Accessioner, which should be ready for general release within a month.

See commit d47a58b4cfbdc20403b745e405a5aecf8dbe25c8

**Comment by sprater** [comment]
Fixed in v. 1.1
